import Link from "next/link";
import { prisma } from "@/lib/prisma";
import { markAttendance } from "./actions";
import { requireRole } from "@/lib/auth-guards";

export const dynamic = "force-dynamic";

export default async function AttendancePage() {
  const session = await requireRole("ADMIN", "TEACHER");
  const teacher = session.user.role === "TEACHER" ? await prisma.teacher.findUnique({ where: { email: session.user.email ?? "" } }) : null;
  const classFilter = teacher ? { teacherId: teacher.id } : {};
  const [records, students, classes] = await prisma.$transaction([prisma.attendanceRecord.findMany({ where: { class: classFilter }, include: { student: true, class: true }, orderBy: { date: "desc" }, take: 100 }), prisma.student.findMany({ where: { status: "ACTIVE", enrollments: { some: { class: classFilter } } }, orderBy: { lastName: "asc" } }), prisma.schoolClass.findMany({ where: classFilter, orderBy: { name: "asc" } })]);
  return <main className="content students-page"><header className="topbar"><div><Link className="back-link" href="/">← Overview</Link><p className="eyebrow">Daily register</p><h1>Attendance</h1></div><Link className="primary-button" href="#mark-attendance">+ <span>Mark attendance</span></Link></header><section className="directory-layout"><div className="panel student-list-panel"><div className="panel-heading"><div><p className="eyebrow">Latest records</p><h2>{records.length} records</h2></div><span className="status-pill green">Up to date</span></div><div className="student-table"><div className="student-row attendance-row student-head"><span>Student</span><span>Class</span><span>Date</span><span>Status</span></div>{records.length === 0 ? <div className="empty-state"><strong>No attendance yet</strong><span>Mark a student&apos;s attendance to begin the register.</span></div> : records.map((record) => <div className="student-row attendance-row" key={record.id}><span><b>{record.student.firstName} {record.student.lastName}</b><small>{record.student.admissionNo}</small></span><span>{record.class.name}</span><span>{record.date.toLocaleDateString()}</span><span className={`status-pill ${record.status === "PRESENT" ? "green" : "orange"}`}>{record.status}</span></div>)}</div></div><div className="panel add-student-panel" id="mark-attendance"><div className="panel-heading"><div><p className="eyebrow">New record</p><h2>Mark attendance</h2></div></div><form action={markAttendance} className="student-form"><label>Student<select name="studentId" required defaultValue=""><option value="" disabled>Select a student</option>{students.map((student) => <option key={student.id} value={student.id}>{student.firstName} {student.lastName} · {student.admissionNo}</option>)}</select></label><label>Class<select name="classId" required defaultValue=""><option value="" disabled>Select a class</option>{classes.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><div className="form-grid"><label>Date<input name="date" type="date" required /><small className="field-help">Duplicate dates update the existing record.</small></label><label>Status<select name="status" defaultValue="PRESENT"><option value="PRESENT">Present</option><option value="ABSENT">Absent</option><option value="LATE">Late</option><option value="EXCUSED">Excused</option></select></label></div><label>Note<input name="note" placeholder="Optional note" /></label><button className="primary-button form-submit" type="submit">Save attendance</button></form></div></section></main>;
}